# Generated by Django 4.0.7 on 2025-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modules_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('approve', models.BooleanField(default=0, null=True)),
                ('reject', models.BooleanField(default=0, null=True)),
                ('dl_login', models.BooleanField(default=0, null=True)),
                ('su_login', models.BooleanField(default=0, null=True)),
                ('su_client_id', models.CharField(max_length=200, null=True)),
                ('dl_client_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('r_approve', models.BooleanField(default=0, null=True)),
                ('r_reject', models.BooleanField(default=0, null=True)),
                ('r_login', models.BooleanField(default=0, null=True)),
                ('r_logout', models.BooleanField(default=0, null=True)),
                ('full_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_done', models.BooleanField(default=0, null=True)),
                ('dl_approve', models.BooleanField(default=False, null=True)),
                ('dl_reject', models.BooleanField(default=False, null=True)),
                ('s_report', models.FileField(blank=True, null=True, upload_to='pdf_reports/')),
                ('pdf_done', models.BooleanField(default=False, null=True)),
                ('f_approve', models.BooleanField(default=False, null=True)),
                ('f_reject', models.BooleanField(default=False, null=True)),
                ('total_done', models.BooleanField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('Br_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('Br_id', models.CharField(max_length=200, null=True)),
                ('f_login', models.BooleanField(default=0, null=True)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('Total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('f_encrypt', models.BooleanField(default=False)),
                ('f_decrypt', models.BooleanField(default=False)),
                ('f_key', models.CharField(max_length=200, null=True)),
                ('f_getkey', models.BooleanField(default=False)),
                ('f_keyenter', models.CharField(max_length=200, null=True)),
                ('f_keycheck', models.BooleanField(default=False)),
                ('dec_food_name', models.CharField(max_length=100, null=True)),
                ('dec_price', models.CharField(max_length=100, null=True)),
                ('dec_quantity', models.CharField(max_length=100, null=True)),
                ('dec_Total_price', models.CharField(max_length=100, null=True)),
                ('su_done', models.BooleanField(default=False)),
                ('Carbon_Footprint', models.FloatField(null=True)),
                ('Water_Usage', models.FloatField(null=True)),
                ('Energy_Consumption', models.FloatField(null=True)),
                ('fview', models.BooleanField(default=False, null=True)),
                ('f_report', models.FileField(blank=True, null=True, upload_to='pdf_reports/')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('payment_done', models.BooleanField(default=0, null=True)),
                ('total_done', models.BooleanField(default=0, null=True)),
            ],
        ),
    ]
